name: Warrior
main: io.github.mcwars.Warrior.Main
version: 1.12
author: McWars Development Team.
description: Core of the McWars Network
softdepend: [EssentialsX]

commands:
    devs:
      description: Lists the developers of Warrior.
      usage: /devs
      permission: Warrior.default
      permission-message: You do not have the permission to execute this command!
      
    freeze:
      description: Freezes a player of your choice.
      usage: /freeze [player]
      permission: Warrior.staff.moderator
      permission-message: You do not have the permission to execute this command!
      
    reop:
      description: Reop's all set Operators. (Managers+)
      usage: /reop
      permission: Warrior.staff.trainee
      permission-message: You do not have the permission to execute this command!
    
    emergencyrestart:
      description: Reop's all set Operators, whitelists the server, then restarts the entire server.
      usage: /emergencyrestart
      permission: Warrior.staff.trainee
      permission-message: You do not have the permission to execute this command! 